version: '3'
services:
    database:
        image: mysql:8.0.18
        container_name: mygel
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 0tvpkdi^hwxmew,
            MYSQL_USER: foo
            MYSQL_PASSWORD: 0tvpkdi^hwxmew,
        volumes:
            - ./data/:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmingel
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8088:80
        environment:
            PMA_HOST: 127.0.0.1
            MYSQL_ROOT_PASSWORD: 0tvpkdi^hwxmew,
    apiservices:
        container_name: apiservicesgel
        ports: 3005:3005

