version: '3'
services:
    portal:
        build: ./portal/.
        container_name: portalgel
        depends_on: 
            - database
        restart: always
        ports:
            - 80:80
    database:
        image: mysql:8.0.18
        container_name: mygel
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 0tvpkdi^hwxmew,
            MYSQL_USER: foo
            MYSQL_PASSWORD: 0tvpkdi^hwxmew,
        volumes:
            - ./data/:/var/lib/mysql
        networks:
            - gelnetwork
    phpmyadmin:
        container_name: phpmyadmingel
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8088:80
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: 0tvpkdi^hwxmew,
        networks:
            - gelnetwork
    apiservices:
        build: ./node
        container_name: apiservicesgel
        ports: 
            - 3005:3005
        networks:
            - gelnetwork
networks:
    gelnetwork:

